# Setup
title: JGCarrillo
description: "Hi, I'm Jorge, welcome to my website!
I'm a software developer based in Murcia (Spain). Here you can find
my latest articles about software development, tips and any other
things related with webs, as well as have a look at my work."
baseurl: /
url: https://jgcarrillo.com/
defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/maquina.jpg
twitter:
  username: jgcarrillo_
  card: summary

# Build settings
plugins:
  - jemoji
  - jekyll-toc
  - jekyll-seo-tag

social:
  twitter: https://github.com/jgcarrillo
  github: https://github.com/jgcarrillo/
