# Setup
title: JGCarrillo
description: 'Desarrollador Web'
baseurl: '/'
url: 'https://www.jgcarrillo.com'
twitter_username: jgcarrillo_
github_username: jgcarrillo

# Build settings
plugins:
  - jemoji
  - jekyll-toc
  - jekyll-seo-tag

social:
  twitter: https://github.com/jgcarrillo
  github: https://github.com/jgcarrillo/
